package com.mygdx.breakout.enums;

public enum Level {
    REALLY_SLOW_TURTLE,
    GIRAFFE_ON_A_BIKE,
    ERIC_CARTMANS_DRONE,
    RABBIT_LATE_FROM_WORK,
    CHINESE_DRAGON_ON_STEROIDS,
    SONIC_THE_HEDGEHOGS_DOG,
    FLASH_TRAVERSING_TIME_SPACE_CONTINUUM
}
